# Generated by Django 5.2.5 on 2025-09-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('date', models.DateField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
