# Generated by Django 5.2.5 on 2025-09-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='highlight_1',
            field=models.TextField(default='highlight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='highlight_2',
            field=models.TextField(default='highlight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='highlight_3',
            field=models.TextField(default='highlight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='highlight_4',
            field=models.TextField(default='highlight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='highlight_5',
            field=models.TextField(default='highlight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='image_1',
            field=models.ImageField(default='page-title-bg.jpg', upload_to='Events_gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='image_2',
            field=models.ImageField(default='page-title-bg.jpg', upload_to='Events_gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='image_3',
            field=models.ImageField(default='page-title-bg.jpg', upload_to='Events_gallery'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EventHighlights',
        ),
    ]
