# Generated by Django 5.2.5 on 2025-10-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_event_highlight_1_event_highlight_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
    ]
