# Generated by Django 5.2.5 on 2025-11-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_event_is_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_1',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='Events_gallery'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_2',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='Events_gallery'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_3',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='Events_gallery'),
        ),
    ]
