# Generated by Django 5.2.5 on 2025-09-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
