# Generated by Django 5.2.4 on 2025-07-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=264, unique=True),
            preserve_default=False,
        ),
    ]
