# Generated by Django 5.2.5 on 2025-09-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_events_address_alter_events_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
