# Generated by Django 5.2.5 on 2025-11-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='blog_image', verbose_name='Add an image'),
        ),
    ]
